### ISSUE TITLE
docker & docker-compose

### ISSUE THREAD

**Issue by nilsnolde** [mbasa/pgrServer#1]
I think it'd make a lot of sense for this repo to have a docker setup. A lot of things could be automated this way, like spinning up a PostGIS/Tomcat instance, creating graphs, easily running on major OSs etc. Would really lower the barrier for getting started.

I can help out a little early next year if you want. Some suggestions:

- ORS has an okish docker setup: https://github.com/GIScience/openrouteservice/blob/master/Dockerfile
- PostGIS best over Kartoza's image IMO (comes with pgrouting3 by default): https://github.com/kartoza/docker-postgis
- probably it makes sense to contain tomcat within the image of this repo similar to ORS

Looking forward to give this a try!

**Comment by mbasa** [comment]
Personally, I don't believe that it is wise to place a server, be it a web server or a database server or an application server like Tomcat, into Docker since the performance and scalability diminishes especially during deployment. 

But I'll gladly accept a PR though since a Docker environment will make sense in a development environment. Thanks.
